version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  rq-worker:
    image: python:3.11
    environment:
      - REDIS_URL=${REDIS_URL}
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -lc "pip install -r requirements.txt && python -m rq worker --url ${REDIS_URL} default"
